 language: scala
 scala:
   - "2.12.2"
 jdk:
   - oraclejdk8

 cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

 script:
  - sbt test:test

 install: sbt ++$TRAVIS_SCALA_VERSION monitoring/publishLocal